

[app]
  port = "8080"

[proxy]
  port = "8081"

[socket]
  port = "8082"

[jwt]
  secret = "xiaoshaoqq@gmail.com,.<>?"
  issuer = "xiaoshaoqq@gmail.com"

[mysql]
  host = "localhost"
  port = 3306
  database = "go_app"
  user = "root"
  password = "123456"
  connection_max = 1000

[redis]
  host = "localhost"
  port = 6379
  db = 5
  password = "123456"

# development environment console out
[logger]
  # filename = "logs/log.log"
  # max_size = 50 # 单个日志文件最多存储量 单位(mb)
  # max_backups = 3 # 志备份文件最多数量  
  # max_age = 50 # 日志保留时间，单位: 天 (day)
  # compress= false # 是否压缩日志
  # logStdout = true # 是否输出到控制台

[email]
  # 163邮箱 POP3/SMTP 服务授权密码
  password =""