[app]
  port = "3000"

[proxy]
  port = "3001"

[socket]
  port = "3002"

[jwt]
  secret = "xiaoshaoqq@gmail.com,.<>?"
  issuer = "xiaoshaoqq@gmail.com"

[database.mysql]
  host = "localhost"
  port = 3306
  database = "go_app"
  user = "root"
  password = "123456"
  connection_max = 1000

[cache.redis]
  host = "localhost"
  port = 6379
  db = 5
  password = "123456"

[logger]
  dir = "logs/"
  http_path = "http/"
  error_path = "error/"

