[app]
  port = "3000"

[proxy]
  port = "3001"

[socket]
  port = "3002"

[jwt]
  secret = "xiaoshaoqq@gmail.com,.<>?"
  issuer = "xiaoshaoqq@gmail.com"

[database.mysql]
# docker mysql service
# Need to be used in docker, if you use another host, please modify
  host = "mysql-service"
  port = 3306
  database = "go_app"
  user = "root"
  password = "123456"
  connection_max = 1000

[cache.redis]
# Docker redis service
# Need to be used in docker, if you use another host, please modify
  host = "redis-service"
  port = 6379
  db = 5
  password = "123456"

[logger]
  dir = "logs/"
  http_path = "http/"
  error_path = "error/"

