[app]
  port = "3000"

[proxy]
  port = "3001"

[socket]
  port = "3002"

[jwt]
  secret = "xiaoshaoqq@gmail.com,.<>?"
  issuer = "xiaoshaoqq@gmail.com"

[mysql]
  # docker mysql service
  # Need to be used in docker, if you use another host, please modify
  host = "mysql-service"
  port = 3306
  database = "go_app"
  user = "root"
  password = "123456"
  connection_max = 1000

[redis]
  # Docker redis service
  # Need to be used in docker, if you use another host, please modify
  host = "redis-service"
  port = 6379
  db = 5
  password = "123456"

[logger]
  filename = "logs/log.log"
  max_size = 50 # 单个日志文件最多存储量 单位(mb)
  max_backups = 10 # 志备份文件最多数量  
  max_age = 100 # 日志保留时间，单位: 天 (day)
  compress= true # 是否压缩日志
